apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencas-admission-server
  namespace: NAMESPACE
  labels:
    app: opencas-admission-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencas-admission-server
  template:
    metadata:
      labels:
        app: opencas-admission-server
    spec:
      containers:
      - name: server
        image: IMAGE
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: tls-certs
          mountPath: /etc/certs
          readOnly: true
      volumes:
      - name: tls-certs
        secret:
          secretName: SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: SERVICE
  namespace: NAMESPACE
spec:
  selector:
    app: opencas-admission-server
  ports:
    - port: 443
      targetPort: 8443
