---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-csi-open-cas-com-v1alpha1-cache
  failurePolicy: Fail
  name: vcache.kb.io
  rules:
  - apiGroups:
    - csi.open-cas.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - caches
  sideEffects: None
