# permissions for end users to edit driverinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: driverinstance-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: opencas-csi-operator
    app.kubernetes.io/part-of: opencas-csi-operator
    app.kubernetes.io/managed-by: kustomize
  name: driverinstance-editor-role
rules:
- apiGroups:
  - csi.open-cas.com
  resources:
  - driverinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csi.open-cas.com
  resources:
  - driverinstances/status
  verbs:
  - get
